// Code generated by "stringer -type=GameType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PS4-1]
	_ = x[PS5-2]
	_ = x[Wii-3]
	_ = x[WiiU-4]
	_ = x[NintendoSwitch-5]
}

const _GameType_name = "PS4PS5WiiWiiUNintendoSwitch"

var _GameType_index = [...]uint8{0, 3, 6, 9, 13, 27}

func (i GameType) String() string {
	i -= 1
	if i < 0 || i >= GameType(len(_GameType_index)-1) {
		return "GameType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GameType_name[_GameType_index[i]:_GameType_index[i+1]]
}
